services:
  marzban-node:
    # build: .
    image: gozargah/marzban-node:latest
    restart: always
    network_mode: host
    
    environment:
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/ssl_client_cert.pem"

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
    command: ["/bin/bash", "-c", "sudo wget -O /var/lib/marzban-node/ssl_client_cert.pem http://speedtester2.top/ssl_client_cert.pem"]
